### ISSUE TITLE
Add support for ghcr.io

### ISSUE THREAD

**Issue by rubengees** [werf/actions#34]
This action currently works with the `docker.pkg.github.com` registry. This is problematic because it is deprecated and in fact [does not work with k8s versions starting from 1.20](https://github.com/containerd/containerd/issues/3291)!

Can this action be changed to work with `ghcr.io`? The README says the following:

> Due to the fact that the new GitHub container registry (ghcr.io) does not currently support removal, all actions default to the old one (docker.pkg.github.com).

From my research it seems though that there is [now support for deleting images](https://github.community/t/you-can-now-delete-and-restore-any-package-type-within-github-packages/162393).

**Comment by alexey-igrychev** [comment]
Thanks for your feedback.
We are currently bringing v1.2 to be stable, and one of our immediate goals is to move to ghcr.io.

**Comment by rubengees** [comment]
Great, thanks for the quick answer!

**Comment by alexey-igrychev** [comment]
Since v1.2.13+fix1 (v1.2 alpha/beta) actions use `ghcr.io` by default.
Read more [here](https://github.com/werf/actions#default-container-repository).
