### ISSUE TITLE
Actions failing - Unexpected HTTP response: 404

### ISSUE THREAD

**Issue by anoutsider** [werf/actions#41]
It seems that all actions have been failing for the past few hours, this is due to the binaries download urls no longer existing, as far as i can tell there  is no way to skip the binary install step or pass it an existing binary, so this is currently affecting all our workflows.

**Response from** https://storage.yandexcloud.net/werf/targets/releases/v1.2.26/werf-linux-amd64-v1.2.26
![image](https://user-images.githubusercontent.com/2252808/136602277-4abd4ac0-0802-4e03-97a6-480fecf02ba5.png)

![image](https://user-images.githubusercontent.com/2252808/136602325-2b258557-a46b-49a7-ad69-be2c4387c6bb.png)

There needs to be a way to install the binary separately to avoid cases like this moving forward.. as it stands now all of our workflows are dead with no way to fix them.

**Comment by alexey-igrychev** [comment]
The problem has now been resolved and I will come back with comments a little later.

I'm sorry for the downtime.

**Comment by anoutsider** [comment]
No worries, thanks for the update

Looking at the code it shouldn't be too hard to allow passing a binary path with exists checks, and on top of that probably move to the trdl/turf release urls.

Can confirm our workflows are working now

**Comment by alexey-igrychev** [comment]
Currently, we are working on the transition from multiwerf to trdl (https://github.com/werf/werf/issues/3674).
As a result, actions will use trdl under the hood.

**Comment by alexey-igrychev** [comment]
solved
